---
- hosts: all
  gather_facts: no
  tasks:
    - win_domain_membership:
        dns_domain_name: "{{ domain }}"
        hostname: "{{ hostname }}"
        domain_admin_user: "{{ domainadmin }}"
        domain_admin_password: "{{ password }}"
        state: domain
      register: domain_state

    - win_reboot:
      when: domain_state.reboot_required


