--- #Disable Repo YUM Only
- hosts: all
  become: yes
  become_method: sudo
  connection: ssh
  
  tasks:
  - name: Disable Repo
    yum_repository:
        name: "{{ item }}"
        state: absent
    notify: yum-clean-metadata
    